name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.11.1, 12.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # caches yarn dependencies in the yarn cache (not npm_modules)
    # should help to speed up yarn install and be safe
    # across changes to the repo and platforms
    - name: Cache Yarn Deps
      uses: c-hive/gha-yarn-cache@v1

    # frozen lockfile should make the cache more effective
    # and our tests more predictable
    - run: yarn install --frozen-lockfile


    - run: yarn test:ci
